package main

import (
	"fmt"
	"time"
)

func runWithTiming(ch chan string, delay, timeout time.Duration) {
	fmt.Printf("Enter routine with delay=%v and timeout=%v\n", delay, timeout)
	go func() {
		time.Sleep(delay)
		ch <- "msg generated by go-routine"
	}()

	fmt.Print("Routine outputs: ")
	select {
	case m := <-ch:
		fmt.Println(m)
	case <-time.After(timeout):
		fmt.Println("timeout generated by select-case-statement")
	}
}

func main() {
	ch := make(chan string, 1)
	runWithTiming(ch, 100*time.Millisecond, 200*time.Millisecond)
	runWithTiming(ch, 300*time.Millisecond, 200*time.Millisecond)
}
